export enum NotificationType {
  RENTAL_CREATED = "RENTAL_CREATED",
  RENTAL_APPROVED = "RENTAL_APPROVED",
  RENTAL_REJECTED = "RENTAL_REJECTED",
  RENTAL_COMPLETED = "RENTAL_COMPLETED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  REFUND_SUCCESS = "REFUND_SUCCESS",
  SYSTEM = "SYSTEM",
}
